### ISSUE TITLE
Integrate `behave` for BDD testing

### ISSUE THREAD

**Issue by nisargthakkar** [nyu-devops-fall19-wishlists/wishlists#129]
**As a** developer  
**I need** to integrate `behave`  
**So that** I can run BDD tests  

**Assumptions:** 
* We will use Gherkin syntax
* We will use behave to run our tests

**Acceptance Criteria:**
```
Given I want to run BDD tests
When I run behave
Then BDD tests should execute
```

**Comment by lombardero** [comment]
Hi! What is the reason we are using `ChromeOptions` instead of `PhantomJS`?

**Comment by lombardero** [comment]
Hi! I am unable to run behave:
There is the following error:
`HOOK-ERROR in before_all: WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
HOOK-ERROR in after_all: AttributeError: 'Context' object has no attribute 'driver'`
