### ISSUE TITLE
[DELETED] Create Swagger account and update Readme

### ISSUE THREAD

**Issue by sflechas** [nyu-devops-fall19-wishlists/wishlists#172]
**As a** developer
**I need** a Swagger account
**So that** the documentation is stored

**Assumptions:** 
* (None)

**Acceptance Criteria:**
```
Given the requirements
When code is updated
Then the swagger documentation is updated.
```

**Comment by lombardero** [comment]
We do not need to add the documentation in SwaggerHub (it requires payment) -> CLOSED
