### ISSUE TITLE
Discuss API Operations and Requirements

### ISSUE THREAD

**Issue by wjduand** [nyu-devops-fall19-wishlists/wishlists#8]
**As a** developer
**I need** to discuss the specific API operations and requirements 
**So that** everyone in the team is clear about what function we are going to implement

**Assumptions:** 
* A Google hangout/Slack/in-person meeting to discuss.

**Acceptance Criteria:**
```
Given a team member
When ask about an API
Then the team member will know exactly the API's functionalities and operations.
```

**Comment by sflechas** [comment]
Wishlists:  A list of items a person wants to buy from a store.  A person can have multiple wish lists.

URL | Operation | Description
-- | -- | --
POST /wishlists | CREATE | Create new Wishlist
POST /wishlists/`<id>`/items | CREATE | Add item to Wishlist
DELETE /wishlists/`<id>` | DELETE | Delete Wishlist
DELETE / wishlists/`<id>`/items/`<itemid>` | DELETE | Delete item from Wishlist
PUT /wishlists/`<id>` | UPDATE | Rename wishlist
GET /wishlists/`<id>`/items | READ | List items in wishlist [ordered chronologically]
GET /wishlists | LIST | Show all wishlists
GET /wishlists?q=querytext | QUERY | Search for a wishlist
GET /wishlists/`<id>`?q=querytext | QUERY | Search for items in wishlist
PUT /wishlists/`<id>`/items/`<itemid>`/add-to-cart | ACTION | Move an item from wishlist to the shopping cart
