### ISSUE TITLE
Fix Add to Cart implementation

### ISSUE THREAD

**Issue by nisargthakkar** [nyu-devops-fall19-wishlists/wishlists#85]
**As a** customer  
**I need** a way to better way to add items from cart  
**So that** I can end up buying them  

**Assumptions:** 
* Add to cart is available and is buggy

**Acceptance Criteria:**
```
Given I have an Item in wishlist
When I add it to cart
Then It should fetch information from Product API invoke ShopCarts API and delete the item from the wishlist
```

**Comment by lombardero** [comment]
I am getting a ```500 - INTERNAL SERVER ERROR``` in Postman after doing the following:
- creating a Wishlist called ```'wishlist1'```
- adding an item ```'apple'``` with ```'product_id = 101'```
- doing the following request: ```PUT``` in ```localhost:5000/wishlists/1/items/101/add-to-cart```
( i am getting a ```200 - OK``` response while doing a ```GET``` request to ```localhost:5000/wishlists/1/items/101```.

Entire Error log:
```File "/vagrant/service/service.py", line 402, in add_to_cart
    wishlist_product.add_to_cart(wishlist.customer_id)
  File "/vagrant/service/models.py", line 259, in add_to_cart
    resp_get_product = Product.get_product_details(self.product_id)
  File "/vagrant/service/models.py", line 288, in get_product_details
    return app.get('/products/%s' % product_id)
NameError: name 'app' is not defined```

Am I doing something wrong?

**Comment by nisargthakkar** [comment]
The problem is that we don't have the other services running, hence we don't know how to connect to them.

**Comment by lombardero** [comment]
Should we then make the system return a generic JSON with the `product_name`, the `customer_id`, and the `product_id`?

I just feel like having a function returning a `500` might not be ideal. Would that be hard to fix?

**Comment by nisargthakkar** [comment]
I can look into it. But if a service is unavailable, `500` would be the correct error code to send. I'll surely fix the reason why it fails (service not found rather than app undefined).
