### ISSUE TITLE
Define model for Database

### ISSUE THREAD

**Issue by lombardero** [nyu-devops-fall19-wishlists/wishlists#9]
**As a** developer
**I need** a Database model  
**So that** I know how to store the data in the Database

**Assumptions:** 
* We decided to use MySql
* The Wishlist database will have two tables:

|WishLists|
|--|
|Wishlist ID|
|Wishlist Name|
|Customer ID|

|WishLists Products|
|--|
|Wishlist ID|
|Product ID|

**Acceptance Criteria:**
```
Given any type of information required to be stored
When anyone wants to add it to the database
Then the structure allows to store it properly
```

**Comment by sflechas** [comment]
The Wishlist database will have two tables:

|WishLists|
|--|
|Wishlist ID|
|Wishlist Name|
|Customer ID|

|WishLists Products|
|--|
|Wishlist ID|
|Product ID|
