### ISSUE TITLE
Enable Travis CI for this organization

### ISSUE THREAD

**Issue by wjduand** [nyu-devops-fall19-wishlists/wishlists#99]
**As a** organization owner  
**I need** enable Travis CI for this organization 
**So that** we can use Travis CI on our repository 

**Assumptions:** 
* Sign on on http://travis-ci.org and grant access of this repository

**Acceptance Criteria:**
```
Given our GitHub organization
When log in to Travis CI
Then this organization is ready to configure.
```

**Comment by wjduand** [comment]
> developer

**Comment by lombardero** [comment]
Do you know why does it shows me the following error:
```The command "nosetests" exited with 4.```

Is that what was supposed to appear? Is it because there are no tests set up yet?

**Comment by wjduand** [comment]
I'm trying to figure out where this error is from. But do you get this error even when there is no .travis.yml file?

**Comment by lombardero** [comment]
I am seing it on the ```add-travis-yml``` branch only, on the ```master``` branch it is ok.

**Comment by wjduand** [comment]
I asked him on Slack but he hasn't replied yet.
